version: '3.8'

services:
  client:
    image: jonathanleedev/sparrow-express-api-kotlin-proxy:latest
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ${SERVER_CERT_PATH}:/etc/nginx/server.crt
      - ${SERVER_KEY_PATH}:/etc/nginx/server.key
  api:
    image: jonathanleedev/sparrow-express-api-kotlin:latest
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: production
      SERVER_CERT_PATH: $SERVER_CERT_PATH
      SERVER_KEY_PATH: $SERVER_KEY_PATH
      DATABASE_URI: $DATABASE_URI
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
      MAIL_USERNAME: $MAIL_USERNAME
      MAIL_PASSWORD: $MAIL_PASSWORD
