spring:
  security:
    oauth2:
      client:
        pre-established-redirect-uri: https://api.sparrow.express/login
        registered-redirect-uri: https://api.sparrow.express/login
        use-current-uri: false
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  data:
    mongodb:
      uri: ${DATABASE_URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
sparrow:
  environment:
    frontEndHost: http://localhost:4200
    googleLoginHost: https://accounts.google.com
