spring:
  data:
    mongodb:
      uri: ${DATABASE_URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
sparrow:
  environment:
    frontEndHost: http://localhost:4200
    googleLoginHost: https://accounts.google.com
